name: CI

on:
  push:
  pull_request:
    branches: ["main"]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        crystal: [1.11.2, 1.12.2, 1.13.3, 1.14.1, 1.15.1, 1.16.3, 1.17.1, 1.18.2, 1.19.2, 1.20.3, 1.21.0]
    runs-on: ubuntu-latest

    services:
      kafka:
        image: apache/kafka:latest
        ports:
          - 9094:9094
        env:
          KAFKA_NODE_ID: 1
          KAFKA_PROCESS_ROLES: broker,controller
          KAFKA_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094
          KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9094
          KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
          KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
          KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
          KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
          KAFKA_NUM_PARTITIONS: 1
        options: >-
          --health-cmd "/opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}

      - name: Install librdkafka
        run: sudo -n apt-get install -qy librdkafka-dev

      - name: Download source
        uses: actions/checkout@v7

      - name: Check formatting
        run: crystal tool format --check

      - name: Run unit tests
        run: crystal spec -v --color spec/kafka spec/rdkafka

      - name: Run integration tests
        run: |
          for test in spec/integration/*_spec.cr; do
            crystal spec -v --color ${test};
          done
        timeout-minutes: 2
